name: Hello World CI # The name of your workflow, shown in the "Actions" tab

on: [push] # The event that triggers the workflow, in this case, any push

jobs: # Groups together all the jobs that run in the workflow
  build: # The name of the job
    runs-on: ubuntu-latest # The type of virtual machine runner the job will run on
    steps: # A sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v4 # Action to check out your repository code
      - name: Run a one-line script # A descriptive name for the step
        run: echo Hello, world! # The command to run in the runner's shell

